### ISSUE TITLE
html-results.html:38 Uncaught TypeError: setState is not a function

### ISSUE THREAD

**Issue by dperez3** [a11smiles/karma-html-detailed-reporter#6]
error
```
html-results.html:38 Uncaught TypeError: setState is not a function
    at HTMLDocument.<anonymous> (http://localhost:51186/_reports/PhantomJS%202.1.1%20(Windows%207%200.0.0)/html-results.html:38:17)
    at i (http://localhost:51186/node_modules/karma-html-detailed-reporter/node_modules/jquery/dist/jquery.min.js:2:27151)
    at Object.fireWith [as resolveWith] (http://localhost:51186/node_modules/karma-html-detailed-reporter/node_modules/jquery/dist/jquery.min.js:2:27914)
    at Function.ready (http://localhost:51186/node_modules/karma-html-detailed-reporter/node_modules/jquery/dist/jquery.min.js:2:29707)
    at HTMLDocument.J (http://localhost:51186/node_modules/karma-html-detailed-reporter/node_modules/jquery/dist/jquery.min.js:2:29892)
```

html-results javascript
```js
            $(document).ready(function() {
                setState(!reload);                

                $('#refreshBtn').click(function() {
                    setState(reload);
                    if (reload) {
                        reload = false;
                    } else {
                        reload = true;
                        refresh();
                    }
                });

                var setState = function(status) {
                    if (status) {
                        $('#refreshBtn').removeClass('btn-danger');
                        $('#refreshBtn').addClass('btn-success');
                        $('#refreshBtn').text('Enable Refresh');
                    } else {
                        $('#refreshBtn').removeClass('btn-success');
                        $('#refreshBtn').addClass('btn-danger');                        
                        $('#refreshBtn').text('Disable Refresh');
                    }                    
                }

                var refresh = function() {
                    if (reload) {
                        location.reload();
                    }
                };
                
                setTimeout(refresh, 1000);
            })
```

karma.conf.js
```js
        reporters: ['progress', 'htmlDetailed'],


        htmlDetailed: {
            autoRefresh: false
        },
```

Seems related to https://github.com/a11smiles/karma-html-detailed-reporter/issues/5

**Comment by b-malone** [comment]
Fwiw, I am also having this same issue about "setState" not being defined in a documeny.ready() enclosure.

I just installed the package today @ version 1.1.12 and Karma version @ 0.13.22.

Also of note, it seems to still show my test results correctly, so it's not necessarily a breaking issue.

This is my error in the console that shows on load:
```
html-results.html:38 Uncaught TypeError: setState is not a function
    at HTMLDocument.<anonymous> (html-results.html:38)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)
```

**Comment by a11smiles** [comment]
hmmm, that's weird.  I'm wondering if it has something to do w/ phantom not liking the `setState()` defined after the function call.  I've adjusted the code in a recent fix.  Get the new version **1.1.13** and see if this is fixed.  Thanks for the head's up.

**Comment by a11smiles** [comment]
closing for the moment.  I think this was fixed in the previous push.  Let me know if I should reopen.
